package com.t.longtv.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.t.longtv.bean.HMTitleBean;
import com.t.longtv.bean.QmTitleBean;
import com.t.longtv.bean.UserLoginBean;

import com.t.longtv.dao.HMTitleBeanDao;
import com.t.longtv.dao.QmTitleBeanDao;
import com.t.longtv.dao.UserLoginBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hMTitleBeanDaoConfig;
    private final DaoConfig qmTitleBeanDaoConfig;
    private final DaoConfig userLoginBeanDaoConfig;

    private final HMTitleBeanDao hMTitleBeanDao;
    private final QmTitleBeanDao qmTitleBeanDao;
    private final UserLoginBeanDao userLoginBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hMTitleBeanDaoConfig = daoConfigMap.get(HMTitleBeanDao.class).clone();
        hMTitleBeanDaoConfig.initIdentityScope(type);

        qmTitleBeanDaoConfig = daoConfigMap.get(QmTitleBeanDao.class).clone();
        qmTitleBeanDaoConfig.initIdentityScope(type);

        userLoginBeanDaoConfig = daoConfigMap.get(UserLoginBeanDao.class).clone();
        userLoginBeanDaoConfig.initIdentityScope(type);

        hMTitleBeanDao = new HMTitleBeanDao(hMTitleBeanDaoConfig, this);
        qmTitleBeanDao = new QmTitleBeanDao(qmTitleBeanDaoConfig, this);
        userLoginBeanDao = new UserLoginBeanDao(userLoginBeanDaoConfig, this);

        registerDao(HMTitleBean.class, hMTitleBeanDao);
        registerDao(QmTitleBean.class, qmTitleBeanDao);
        registerDao(UserLoginBean.class, userLoginBeanDao);
    }
    
    public void clear() {
        hMTitleBeanDaoConfig.clearIdentityScope();
        qmTitleBeanDaoConfig.clearIdentityScope();
        userLoginBeanDaoConfig.clearIdentityScope();
    }

    public HMTitleBeanDao getHMTitleBeanDao() {
        return hMTitleBeanDao;
    }

    public QmTitleBeanDao getQmTitleBeanDao() {
        return qmTitleBeanDao;
    }

    public UserLoginBeanDao getUserLoginBeanDao() {
        return userLoginBeanDao;
    }

}
